### ISSUE TITLE
Support for 1.20.4

### ISSUE THREAD

**Issue by Zorklis** [mrmelon54/draggable_lists#11]
Doesn't cause a crash when launching into minecraft but when pressed into resource pack section it crashes.

Really useful mod, I love it, please update it :)

**Comment by Zorklis** [comment]
Still wish for the support

**Comment by Zorklis** [comment]
Update, "draggable_lists-mc1.20.2-1.0.2-build.13.jar" is out and it's supposed to support versions 1.20–1.20.4.
Tried it and pressing on Resource packs button it crashed the game, log:
[crash-2024-01-09_10.03.14-client.txt](https://github.com/mrmelon54/draggable_lists/files/13870789/crash-2024-01-09_10.03.14-client.txt)

**Comment by mrmelon54** [comment]
Done

**Comment by Zorklis** [comment]
Seems to work just fine :) , thank you
