### ISSUE TITLE
Crash 1.20.1 - v1.0.2

### ISSUE THREAD

**Issue by 909oce** [mrmelon54/draggable_lists#12]
Clicking on multiplayer causes game to crash with [this log](https://mclo.gs/bUJE1u3)

**Comment by DeshiDesu** [comment]
Seems incompatible with [redirector](https://www.curseforge.com/minecraft/mc-mods/redirectionor)

**Comment by Quotions** [comment]
Same

**Comment by mrmelon54** [comment]
Fixed in 1.20.4
