### ISSUE TITLE
Backport to 1.20.1

### ISSUE THREAD

**Issue by Poopooracoocoo** [mrmelon54/draggable_lists#17]
[Draggable Lists 1.0.2](https://modrinth.com/mod/draggable-lists/version/cHA0Q7Oi) crashes on launch with required dependencies as per FMJ. Also had a look at the Modrinth version page which had no dependencies listed, and had a look at the Modrinth description, which seems to be for before this went multi-loader. The `Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData` error itself is what tells users that Cloth Config is required. 

And then there are crashes such as when one clicks on the resource packs screen that were only fixed in versions for 1.20.4:
https://github.com/mrmelon54/draggable_lists/issues/12
https://github.com/mrmelon54/draggable_lists/issues/13

1.20.1 is the de facto target for modpacks in the 1.20 lifecycle so many won't see fixes to these issues.

**Comment by mrmelon54** [comment]
And does it work fine when and add cloth config.

Bare in mind that changes in the latest 1.20.4 release improve the handling of dependencies and version numbers in the mod metadata file for each platform.

**Comment by Poopooracoocoo** [comment]
[draggable_lists-mc1.20-1.0.1-build.7.jar](https://modrinth.com/mod/draggable-lists/version/1.0.1) and [draggable_lists-mc1.20-1.0.0-build.5.jar](https://modrinth.com/mod/draggable-lists/version/1.0.0) work on 1.20.1. 

I suspect that [draggable_lists-mc1.20.2-1.0.2-build.13.jar](https://modrinth.com/mod/draggable-lists/version/cHA0Q7Oi) is mistakenly marked as being for 1.20.1 on Modrinth.

**Comment by mrmelon54** [comment]
Fixed
