### ISSUE TITLE
Mark 1.0.1 release as compatible with Minecraft 1.20.1

### ISSUE THREAD

**Issue by Felix14-v2** [mrmelon54/draggable_lists#2]
This version isn't specified as compatible with 1.20.1 on Modrinth, so users can't automatically update to it using Modrinth App
![image](https://github.com/MrMelon54/draggable_lists/assets/75726196/3d5fe615-8933-4bf7-b18f-8fd550be1646)

**Comment by MrMelon54** [comment]
Issue fixed 👍
