### ISSUE TITLE
Incompatiblities

### ISSUE THREAD

**Issue by QwertRvg** [mrmelon54/draggable_lists#21]
The game crashes before even loading up when these mods are installed alongside Draggable Lists:

- Remove Reloading Screen
- Panorama Screens

**Comment by QwertRvg** [comment]
oh yea, Minecraft 1.20.1 and Forge 47.2.0

**Comment by QwertRvg** [comment]
okay the problem seems to have been because of the mod id issue

**Comment by mrmelon54** [comment]
Duplicate of #20
