### ISSUE TITLE
Versions bug

### ISSUE THREAD

**Issue by mpustovoi** [mrmelon54/draggable_lists#23]
So basically y custom modpack constantly suggests updating your mod, as it has two primary files (`Fabric 1.20.1`).
This will never stop unless I edit the mod file as an archive.
![image](https://github.com/mrmelon54/draggable_lists/assets/92390626/de63791d-2588-4e58-9c78-3b1acf283801)

**Comment by mrmelon54** [comment]
That was probably added by my automatic build system, I have remove the 1.0.1-fix version and deleted the old build.7 jar
