### ISSUE TITLE
Draggable lists Causes my minecraft to crash 

### ISSUE THREAD

**Issue by amawdiin** [mrmelon54/draggable_lists#9]
LOGS:
[tl-logger8727151911583265392.txt](https://github.com/MrMelon54/draggable_lists/files/13062814/tl-logger8727151911583265392.txt)
MODLIST: 
![image](https://github.com/MrMelon54/draggable_lists/assets/123622161/5b135eaf-4ce4-4c5e-9aef-bfcb6776700d)
there are no other error messages about incompatibility, missing dependencies etc, but when i remove draggable lists from my mods folder it just works

**Comment by mrmelon54** [comment]
Missing cloth config

**Comment by mrmelon54** [comment]
In newer versions of the mod I have cloth config properly listed as a dependency
